version: "3"

services:
  redistimeseries:
    container_name: redislabs-redistimeseries
    image: redislabs/redistimeseries:latest
  node:
    container_name: redis-time-series
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
