export enum CommandKeyword {
    LABELS = "LABELS",
    RETENTION = "RETENTION",
    AGGREGATION = "AGGREGATION",
    TIMESTAMP = "TIMESTAMP",
    MIN_TIMESTAMP = "-",
    MAX_TIMESTAMP = "+",
    CURRENT_TIMESTAMP = "*",
    COUNT = "COUNT",
    FILTER = "FILTER",
    WITHLABELS = "WITHLABELS",
    UNCOMPRESSED = "UNCOMPRESSED"
}
