export enum CommandKeyword {
    LABELS = "LABELS",
    RETENTION = "RETENTION",
    AGGREGATION = "AGGREGATION",
    TIMESTAMP = "TIMESTAMP",
    MIN_TIMESTAMP = "-",
    MAX_TIMESTAMP = "+",
    CURRENT_TIMESTAMP = "*",
    COUNT = "COUNT",
    FILTER = "FILTER",
    WITHLABELS = "WITHLABELS",
    UNCOMPRESSED = "UNCOMPRESSED",
    CHUNK_SIZE = "CHUNK_SIZE",
    DUPLICATE_POLICY = "DUPLICATE_POLICY",
    ON_DUPLICATE = "ON_DUPLICATE"
}
